apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: user-service-deployment
spec:
  replicas: 2 
  selector: 
    matchLabels: 
      app: user-service
  template: 
    metadata:
      labels: 
        app: user-service
    spec: 
      containers: 
      - name: user-service-nodongo
        image: kjasir23/ccet-ia2:1.1
        imagePullPolicy: Never
        ports: 
        - containerPort: 3000